### PR TITLE
fix: add compilers to npm package

### PR DESCRIPTION
**Pull request by raymondfeng**
### Description

Add `compilers` to npm package.

#### Related issues

- connect to #27

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by amritaramnauth** [comment]
Is this fix applied in v0.1.1? I still get the missing compilers error..

**Comment by Klypalskyi** [comment]
And me to have the same error
image

**Comment by Klypalskyi** [comment]
Resolved with next steps:

1. create folders at node_modules/@loopback/grpc -> compilers/linux/bin;
2. copy **protoc** file from /bin to node_modules/@loopback/grpc/compilers/linux/bin

**Comment by Klypalskyi** [comment]
@raymondfeng it looks excellent! Thank you!

**Pull request merged**
